In [0]:
import pandas as pd

In [0]:
filename1 = 'Breast_cancer_data.csv'
filename2 = 'diabetes.csv'
data1 = pd.read_csv(filename1) 
data2 = pd.read_csv(filename2)

In [0]:
type(data1)
type(data2)
# DataFrame created

pandas.core.frame.DataFrame

In [0]:
data1.head(0)

Empty DataFrame
Columns: [mean_radius, mean_texture, mean_perimeter, mean_area, mean_smoothness, diagnosis]
Index: []

In [0]:
data2.head(0)

Empty DataFrame
Columns: [Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age, Outcome]
Index: []

In [0]:
# column-wise
print(data1.mean(axis = 0))

mean_radius         14.127292
mean_texture        19.289649
mean_perimeter      91.969033
mean_area          654.889104
mean_smoothness      0.096360
diagnosis            0.627417
dtype: float64

In [0]:
# row-wise
print(data1.mean(axis = 1))

0      192.048067
1      249.554123
2      229.008267
3       82.603750
4      244.471717
5       97.991300
6      199.654105
7      117.126483
8      107.041217
9       99.414767
10     156.640343
11     153.061183
12     216.577900
13     154.380668
14     118.058850
15     132.953983
16     135.691445
17     157.304500
18     238.676385
19     113.792965
20     105.921250
21      59.547733
22     139.434550
23     264.249047
24     175.457017
25     177.059767
26     129.737567
27     209.175733
28     145.913033
29     183.803078
          ...
539     42.159613
540     84.104973
541    132.126395
542    134.090458
543    110.939452
544    118.372630
545    116.388743
546     69.662390
547     69.096462
548     62.809652
549     77.766987
550     77.070718
551     80.759277
552    105.422127
553     59.229233
554    106.613538
555     71.010050
556     67.880050
557     61.490705
558    131.974122
559     85.758768
560    122.346548
561     83.052415
562    144.374133
563    256.019983
564    277.510167
565    240.112967
566    168.527425
567    242.524633
568     43.712105
Length: 569, dtype: float64

In [0]:
data1[['mean_texture']].mean(axis = 0)

mean_texture    19.289649
dtype: float64

In [0]:
print(data1.median(axis = 0))

mean_radius         13.37000
mean_texture        18.84000
mean_perimeter      86.24000
mean_area          551.10000
mean_smoothness      0.09587
diagnosis            1.00000
dtype: float64

In [0]:
print(data1.median(axis = 1))

0      14.1850
1      19.1700
2      20.4700
3      15.9000
4      17.3150
5      14.0750
6      19.1150
7      17.2700
8      17.4100
9      18.2500
10     19.6300
11     16.8350
12     21.9850
13     19.9000
14     18.1700
15     21.0400
16     17.4050
17     18.4050
18     20.9800
19     13.9500
20     14.3950
21     10.9720
22     14.8000
23     22.1000
24     19.0150
25     16.7700
26     18.0550
27     19.4300
28     20.2850
29     16.3100
        ...
539    16.5655
540    12.9900
541    19.7300
542    20.0800
543    20.6350
544    17.2850
545    18.4250
546    13.3350
547    13.4200
548    14.5115
549    17.5150
550    16.1700
551    16.7850
552    21.1000
553    15.6365
554    20.9000
555    18.9500
556    14.8750
557    18.6515
558    18.6350
559    17.7200
560    20.6000
561    20.2850
562    22.9200
563    23.0050
564    21.9750
565    24.1900
566    22.3400
567    24.9650
568    16.1500
Length: 569, dtype: float64

In [0]:
data1[['mean_texture']].median(axis = 0)

mean_texture    18.84
dtype: float64

In [0]:
print(data1.mode(axis = 0))

   mean_radius  mean_texture  ...  mean_smoothness  diagnosis
0        12.34         14.93  ...           0.1007        1.0
1          NaN         15.70  ...              NaN        NaN
2          NaN         16.84  ...              NaN        NaN
3          NaN         16.85  ...              NaN        NaN
4          NaN         17.46  ...              NaN        NaN
5          NaN         18.22  ...              NaN        NaN
6          NaN         18.90  ...              NaN        NaN
7          NaN         19.83  ...              NaN        NaN
8          NaN         20.52  ...              NaN        NaN

[9 rows x 6 columns]

In [0]:
print(data1.mode(axis = 1))

           0        1       2      3       4       5
0    0.00000  0.11840  10.380  17.99  122.80  1001.0
1    0.00000  0.08474  17.770  20.57  132.90  1326.0
2    0.00000  0.10960  19.690  21.25  130.00  1203.0
3    0.00000  0.14250  11.420  20.38   77.58   386.1
4    0.00000  0.10030  14.340  20.29  135.10  1297.0
5    0.00000  0.12780  12.450  15.70   82.57   477.1
6    0.00000  0.09463  18.250  19.98  119.60  1040.0
7    0.00000  0.11890  13.710  20.83   90.20   577.9
8    0.00000  0.12730  13.000  21.82   87.50   519.8
9    0.00000  0.11860  12.460  24.04   83.97   475.9
10   0.00000  0.08206  16.020  23.24  102.70   797.8
11   0.00000  0.09710  15.780  17.89  103.60   781.0
12   0.00000  0.09740  19.170  24.80  132.40  1123.0
13   0.00000  0.08401  15.850  23.95  103.70   782.7
14   0.00000  0.11310  13.730  22.61   93.60   578.3
15   0.00000  0.11390  14.540  27.54   96.73   658.8
16   0.00000  0.09867  14.680  20.13   94.74   684.5
17   0.00000  0.11700  16.130  20.68  108.10   798.8
18   0.00000  0.09831  19.810  22.15  130.00  1260.0
19   0.09779  1.00000  13.540  14.36   87.46   566.3
20   0.10750  1.00000  13.080  15.71   85.63   520.0
21   0.10240  1.00000   9.504  12.44   60.34   273.9
22   0.00000  0.10730  14.260  15.34  102.50   704.4
23   0.00000  0.09428  21.160  23.04  137.20  1404.0
24   0.00000  0.11210  16.650  21.38  110.00   904.6
25   0.00000  0.11860  16.400  17.14  116.00   912.7
26   0.00000  0.10540  14.580  21.53   97.41   644.8
27   0.00000  0.09440  18.610  20.25  122.10  1094.0
28   0.00000  0.10820  15.300  25.27  102.40   732.4
29   0.00000  0.09847  15.050  17.57  115.00   955.1
..       ...      ...     ...    ...     ...     ...
539  0.08668  1.00000   7.691  25.44   48.34   170.4
540  0.09984  1.00000  11.540  14.44   74.65   402.9
541  0.08837  1.00000  14.470  24.99   95.81   656.4
542  0.08275  1.00000  14.740  25.42   94.70   668.6
543  0.08671  1.00000  13.210  28.06   84.88   538.4
544  0.09578  1.00000  13.870  20.70   89.77   584.8
545  0.09246  1.00000  13.620  23.23   87.19   573.2
546  0.09434  1.00000  10.320  16.35   65.31   324.9
547  0.08877  1.00000  10.260  16.58   65.85   320.8
548  0.08491  1.00000   9.683  19.34   61.05   285.7
549  0.08192  1.00000  10.820  24.21   68.89   361.6
550  0.07431  1.00000  10.860  21.48   68.51   360.5
551  0.09566  1.00000  11.130  22.44   71.49   378.4
552  0.08276  1.00000  12.770  29.43   81.35   507.9
553  0.09240  1.00000   9.333  21.94   59.01   264.0
554  0.08123  1.00000  12.880  28.92   82.50   514.3
555  0.09030  1.00000  10.290  27.61   65.67   321.4
556  0.10030  1.00000  10.160  19.59   64.73   311.7
557  0.08123  1.00000   9.423  27.88   59.26   271.3
558  0.08473  1.00000  14.590  22.68   96.39   657.1
559  0.09261  1.00000  11.510  23.93   74.52   403.5
560  0.09929  1.00000  14.050  27.15   91.38   600.4
561  0.07449  1.00000  11.200  29.37   70.67   386.0
562  0.00000  0.10480  15.220  30.62  103.40   716.9
563  0.00000  0.10990  20.920  25.09  143.00  1347.0
564  0.00000  0.11100  21.560  22.39  142.00  1479.0
565  0.00000  0.09780  20.130  28.25  131.20  1261.0
566  0.00000  0.08455  16.600  28.08  108.30   858.1
567  0.00000  0.11780  20.600  29.33  140.10  1265.0
568  0.05263  1.00000   7.760  24.54   47.92   181.0

[569 rows x 6 columns]

In [0]:
data1[['mean_texture']].mode(axis = 0)

   mean_texture
0         14.93
1         15.70
2         16.84
3         16.85
4         17.46
5         18.22
6         18.90
7         19.83
8         20.52

In [0]:
print(data1.std(axis = 0))

mean_radius          3.524049
mean_texture         4.301036
mean_perimeter      24.298981
mean_area          351.914129
mean_smoothness      0.014064
diagnosis            0.483918
dtype: float64

In [0]:
print(data1.std(axis = 1))

0      399.053249
1      529.719502
2      479.641440
3      151.457829
4      518.165961
5      188.271057
6      414.117341
7      228.216844
8      204.815276
9      187.064258
10     316.421141
11     310.063437
12     446.812126
13     310.224908
14     228.150930
15     260.108992
16     271.169186
17     316.855383
18     502.709572
19     224.072515
20     205.346308
21     107.361651
22     279.453868
23     560.723298
24     359.562098
25     363.025916
26     254.927778
27     435.883904
28     289.835993
29     380.335325
          ...
539     65.445657
540    158.620206
541    259.280196
542    264.188189
543    211.753006
544    230.910845
545    226.101059
546    127.344531
547    125.685407
548    111.489983
549    141.363623
550    141.134568
551    148.184652
552    199.463023
553    102.663572
554    202.047187
555    125.080094
556    121.810229
557    105.162627
558    259.729354
559    158.078598
560    236.623723
561    150.726951
562    283.105306
563    537.149472
564    591.016041
565    502.516131
566    340.211580
567    503.632494
568     69.650943
Length: 569, dtype: float64

In [0]:
data1[['mean_texture']].std(axis = 0)

mean_texture    4.301036
dtype: float64

In [0]:
# Displaying first 2 rows and first 2 columns
data1.iloc[: 2, : 2]

   mean_radius  mean_texture
0        17.99         10.38
1        20.57         17.77

In [0]:
data1.iloc[:, [1, 2]]

     mean_texture  mean_perimeter
0           10.38          122.80
1           17.77          132.90
2           21.25          130.00
3           20.38           77.58
4           14.34          135.10
5           15.70           82.57
6           19.98          119.60
7           20.83           90.20
8           21.82           87.50
9           24.04           83.97
10          23.24          102.70
11          17.89          103.60
12          24.80          132.40
13          23.95          103.70
14          22.61           93.60
15          27.54           96.73
16          20.13           94.74
17          20.68          108.10
18          22.15          130.00
19          14.36           87.46
20          15.71           85.63
21          12.44           60.34
22          14.26          102.50
23          23.04          137.20
24          21.38          110.00
25          16.40          116.00
26          21.53           97.41
27          20.25          122.10
28          25.27          102.40
29          15.05          115.00
..            ...             ...
539         25.44           48.34
540         14.44           74.65
541         24.99           95.81
542         25.42           94.70
543         28.06           84.88
544         20.70           89.77
545         23.23           87.19
546         16.35           65.31
547         16.58           65.85
548         19.34           61.05
549         24.21           68.89
550         21.48           68.51
551         22.44           71.49
552         29.43           81.35
553         21.94           59.01
554         28.92           82.50
555         27.61           65.67
556         19.59           64.73
557         27.88           59.26
558         22.68           96.39
559         23.93           74.52
560         27.15           91.38
561         29.37           70.67
562         30.62          103.40
563         25.09          143.00
564         22.39          142.00
565         28.25          131.20
566         28.08          108.30
567         29.33          140.10
568         24.54           47.92

[569 rows x 2 columns]

In [0]:
data1.min()

mean_radius          6.98100
mean_texture         9.71000
mean_perimeter      43.79000
mean_area          143.50000
mean_smoothness      0.05263
diagnosis            0.00000
dtype: float64

In [0]:
data1.max()

mean_radius          28.1100
mean_texture         39.2800
mean_perimeter      188.5000
mean_area          2501.0000
mean_smoothness       0.1634
diagnosis             1.0000
dtype: float64

In [0]:
data1.max(1)

0      1001.0
1      1326.0
2      1203.0
3       386.1
4      1297.0
5       477.1
6      1040.0
7       577.9
8       519.8
9       475.9
10      797.8
11      781.0
12     1123.0
13      782.7
14      578.3
15      658.8
16      684.5
17      798.8
18     1260.0
19      566.3
20      520.0
21      273.9
22      704.4
23     1404.0
24      904.6
25      912.7
26      644.8
27     1094.0
28      732.4
29      955.1
        ...
539     170.4
540     402.9
541     656.4
542     668.6
543     538.4
544     584.8
545     573.2
546     324.9
547     320.8
548     285.7
549     361.6
550     360.5
551     378.4
552     507.9
553     264.0
554     514.3
555     321.4
556     311.7
557     271.3
558     657.1
559     403.5
560     600.4
561     386.0
562     716.9
563    1347.0
564    1479.0
565    1261.0
566     858.1
567    1265.0
568     181.0
Length: 569, dtype: float64

In [0]:
data1.min(1)

0      0.00000
1      0.00000
2      0.00000
3      0.00000
4      0.00000
5      0.00000
6      0.00000
7      0.00000
8      0.00000
9      0.00000
10     0.00000
11     0.00000
12     0.00000
13     0.00000
14     0.00000
15     0.00000
16     0.00000
17     0.00000
18     0.00000
19     0.09779
20     0.10750
21     0.10240
22     0.00000
23     0.00000
24     0.00000
25     0.00000
26     0.00000
27     0.00000
28     0.00000
29     0.00000
        ...
539    0.08668
540    0.09984
541    0.08837
542    0.08275
543    0.08671
544    0.09578
545    0.09246
546    0.09434
547    0.08877
548    0.08491
549    0.08192
550    0.07431
551    0.09566
552    0.08276
553    0.09240
554    0.08123
555    0.09030
556    0.10030
557    0.08123
558    0.08473
559    0.09261
560    0.09929
561    0.07449
562    0.00000
563    0.00000
564    0.00000
565    0.00000
566    0.00000
567    0.00000
568    0.05263
Length: 569, dtype: float64

In [0]:
data1['diagnosis'].unique()

array([0, 1])

In [0]:
print("\n -- loc -- \n")
print(data1.loc[data1['mean_texture'] < 20, ['mean_perimeter', 'diagnosis']])

 -- loc --

     mean_perimeter  diagnosis
0            122.80          0
1            132.90          0
4            135.10          0
5             82.57          0
6            119.60          0
11           103.60          0
19            87.46          1
20            85.63          1
21            60.34          1
22           102.50          0
25           116.00          0
29           115.00          0
31            77.93          0
34           107.00          0
37            82.61          1
45           123.70          0
46            51.71          1
47            85.98          0
48            78.04          1
51            87.21          1
52            75.71          1
53           120.30          0
55            73.34          1
56           125.50          0
58            82.61          1
59            54.34          1
60            64.55          1
63            59.20          1
67            71.80          1
68            58.79          1
..              ...        ...
502           81.25          1
503          152.10          0
504           61.49          1
505           64.12          1
507           71.25          1
508          104.70          1
510           76.31          1
511           94.66          1
513           94.29          1
514           97.26          0
515           72.76          1
518           84.45          1
519           82.51          1
520           59.96          1
522           71.30          1
523           88.73          1
524           63.00          1
525           54.53          1
526           87.44          1
527           78.94          1
528           90.31          1
529           77.83          1
530           75.89          1
532           87.76          1
534           70.79          1
540           74.65          1
546           65.31          1
547           65.85          1
548           61.05          1
556           64.73          1

[344 rows x 2 columns]

In [0]:
print(data1.iloc[(data1['mean_texture'] < 20).values, [1, 3]])

     mean_texture  mean_area
0           10.38     1001.0
1           17.77     1326.0
4           14.34     1297.0
5           15.70      477.1
6           19.98     1040.0
11          17.89      781.0
19          14.36      566.3
20          15.71      520.0
21          12.44      273.9
22          14.26      704.4
25          16.40      912.7
29          15.05      955.1
31          18.70      440.6
34          17.88      807.2
37          18.42      523.8
45          17.60     1076.0
46          16.84      201.9
47          18.66      534.6
48          14.63      449.3
51          16.34      571.8
52          18.24      437.6
53          18.70     1033.0
55          18.75      409.0
56          18.57     1152.0
58          19.31      527.2
59          11.79      224.5
60          14.88      311.9
63          13.86      260.9
67          19.04      394.1
68          17.33      250.5
..            ...        ...
502         16.32      476.3
503         19.83     1682.0
504         12.87      248.7
505         13.14      272.5
507         17.12      366.5
508         15.70      819.8
510         14.69      426.0
511         14.70      680.7
513         13.66      658.8
514         19.07      701.9
515         18.61      391.2
518         18.22      493.1
519         16.70      493.8
520         13.90      257.8
522         19.83      388.1
523         18.68      571.0
524         15.68      293.2
525         13.10      221.3
526         18.75      551.1
527         12.27      468.5
528         13.17      594.2
529         13.44      445.2
530         17.56      422.9
532         16.33      575.5
534         17.62      365.6
540         14.44      402.9
546         16.35      324.9
547         16.58      320.8
548         19.34      285.7
556         19.59      311.7

[344 rows x 2 columns]

In [0]:
data1.shape

(569, 6)

In [0]:
from sklearn import preprocessing

In [0]:
x = data1.values # returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
df = pd.DataFrame(x_scaled)

In [0]:
df

            0         1         2         3         4    5
0    0.521037  0.022658  0.545989  0.363733  0.593753  0.0
1    0.643144  0.272574  0.615783  0.501591  0.289880  0.0
2    0.601496  0.390260  0.595743  0.449417  0.514309  0.0
3    0.210090  0.360839  0.233501  0.102906  0.811321  0.0
4    0.629893  0.156578  0.630986  0.489290  0.430351  0.0
5    0.258839  0.202570  0.267984  0.141506  0.678613  0.0
6    0.533343  0.347311  0.523875  0.380276  0.379164  0.0
7    0.318472  0.376057  0.320710  0.184263  0.598267  0.0
8    0.284869  0.409537  0.302052  0.159618  0.674099  0.0
9    0.259312  0.484613  0.277659  0.140997  0.595558  0.0
10   0.427801  0.457558  0.407090  0.277540  0.265686  0.0
11   0.416442  0.276632  0.413309  0.270414  0.401462  0.0
12   0.576885  0.510315  0.612328  0.415483  0.404171  0.0
13   0.419755  0.481569  0.414000  0.271135  0.283290  0.0
14   0.319419  0.436253  0.344206  0.184433  0.545906  0.0
15   0.357755  0.602976  0.365835  0.218579  0.553128  0.0
16   0.364381  0.352384  0.352083  0.229480  0.415636  0.0
17   0.433007  0.370984  0.444406  0.277964  0.581114  0.0
18   0.607175  0.420697  0.595743  0.473595  0.412386  0.0
19   0.310426  0.157254  0.301776  0.179343  0.407692  1.0
20   0.288655  0.202908  0.289130  0.159703  0.495351  1.0
21   0.119409  0.092323  0.114367  0.055313  0.449309  1.0
22   0.395617  0.153872  0.405708  0.237922  0.493545  0.0
23   0.671068  0.450795  0.645498  0.534677  0.376004  0.0
24   0.457617  0.394657  0.457536  0.322842  0.536878  0.0
25   0.480808  0.226243  0.498998  0.326278  0.595558  0.0
26   0.359648  0.399729  0.370534  0.212641  0.476393  0.0
27   0.550381  0.356442  0.541151  0.403181  0.377088  0.0
28   0.393724  0.526209  0.405017  0.249799  0.501670  0.0
29   0.501160  0.180588  0.492088  0.344263  0.413830  0.0
..        ...       ...       ...       ...       ...  ...
539  0.033603  0.531958  0.031442  0.011410  0.307394  1.0
540  0.215770  0.159959  0.213254  0.110032  0.426198  1.0
541  0.354442  0.516740  0.359478  0.217561  0.322651  1.0
542  0.367220  0.531282  0.351807  0.222736  0.271915  1.0
543  0.294808  0.620561  0.283947  0.167508  0.307665  1.0
544  0.326045  0.371660  0.317739  0.187190  0.389546  1.0
545  0.314213  0.457220  0.299910  0.182269  0.359574  1.0
546  0.158029  0.224552  0.148711  0.076946  0.376546  1.0
547  0.155190  0.232330  0.152443  0.075207  0.326262  1.0
548  0.127881  0.325668  0.119273  0.060318  0.291415  1.0
549  0.181693  0.490362  0.173450  0.092513  0.264422  1.0
550  0.183587  0.398039  0.170824  0.092047  0.195721  1.0
551  0.196365  0.430504  0.191417  0.099639  0.388463  1.0
552  0.273984  0.666892  0.259554  0.154571  0.272005  1.0
553  0.111316  0.413595  0.105176  0.051113  0.359032  1.0
554  0.279190  0.649645  0.267501  0.157285  0.258193  1.0
555  0.156609  0.605343  0.151199  0.075461  0.340074  1.0
556  0.150457  0.334122  0.144703  0.071347  0.430351  1.0
557  0.115576  0.614474  0.106903  0.054210  0.258193  1.0
558  0.360121  0.438620  0.363486  0.217858  0.289790  1.0
559  0.214350  0.480893  0.212356  0.110286  0.360928  1.0
560  0.334564  0.589787  0.328865  0.193807  0.421233  1.0
561  0.199678  0.664863  0.185751  0.102863  0.197346  1.0
562  0.389938  0.707136  0.411927  0.243224  0.470976  0.0
563  0.659709  0.520122  0.685578  0.510498  0.517017  0.0
564  0.690000  0.428813  0.678668  0.566490  0.526948  0.0
565  0.622320  0.626987  0.604036  0.474019  0.407782  0.0
566  0.455251  0.621238  0.445788  0.303118  0.288165  0.0
567  0.644564  0.663510  0.665538  0.475716  0.588336  0.0
568  0.036869  0.501522  0.028540  0.015907  0.000000  1.0

[569 rows x 6 columns]

In [0]:
df.mean()

0    0.338222
1    0.323965
2    0.332935
3    0.216920
4    0.394785
5    0.627417
dtype: float64

In [0]:
df.std()

0    0.166787
1    0.145453
2    0.167915
3    0.149274
4    0.126967
5    0.483918
dtype: float64

In [0]:
data1.mean()

mean_radius         14.127292
mean_texture        19.289649
mean_perimeter      91.969033
mean_area          654.889104
mean_smoothness      0.096360
diagnosis            0.627417
dtype: float64

In [0]:
data1.std()

mean_radius          3.524049
mean_texture         4.301036
mean_perimeter      24.298981
mean_area          351.914129
mean_smoothness      0.014064
diagnosis            0.483918
dtype: float64

In [0]:
data1.head()

   mean_radius  mean_texture  ...  mean_smoothness  diagnosis
0        17.99         10.38  ...          0.11840          0
1        20.57         17.77  ...          0.08474          0
2        19.69         21.25  ...          0.10960          0
3        11.42         20.38  ...          0.14250          0
4        20.29         14.34  ...          0.10030          0

[5 rows x 6 columns]

In [0]:
dataframe = (data1 - data1.mean()) / data1.std()

In [0]:
dataframe

     mean_radius  mean_texture  ...  mean_smoothness  diagnosis
0       1.096100     -2.071512  ...         1.567087  -1.296535
1       1.828212     -0.353322  ...        -0.826235  -1.296535
2       1.578499      0.455786  ...         0.941382  -1.296535
3      -0.768233      0.253509  ...         3.280667  -1.296535
4       1.748758     -1.150804  ...         0.280125  -1.296535
5      -0.475956     -0.834601  ...         2.235455  -1.296535
6       1.169878      0.160508  ...        -0.123028  -1.296535
7      -0.118413      0.358135  ...         1.602639  -1.296535
8      -0.319885      0.588312  ...         2.199903  -1.296535
9      -0.473118      1.104467  ...         1.581308  -1.296535
10      0.537083      0.918465  ...        -1.016791  -1.296535
11      0.468980     -0.325421  ...         0.052596  -1.296535
12      1.430942      1.281168  ...         0.073927  -1.296535
13      0.488843      1.083542  ...        -0.878141  -1.296535
14     -0.112737      0.771989  ...         1.190242  -1.296535
15      0.117112      1.918224  ...         1.247125  -1.296535
16      0.156839      0.195384  ...         0.164228  -1.296535
17      0.568298      0.323260  ...         1.467543  -1.296535
18      1.612551      0.665038  ...         0.138631  -1.296535
19     -0.166653     -1.146154  ...         0.101657   0.769931
20     -0.297184     -0.832276  ...         0.792066   0.769931
21     -1.311926     -1.592558  ...         0.429441   0.769931
22      0.344124     -1.169404  ...         0.777846  -1.296535
23      1.995633      0.871965  ...        -0.147914  -1.296535
24      0.715855      0.486011  ...         1.119139  -1.296535
25      0.854900     -0.671849  ...         1.581308  -1.296535
26      0.128463      0.520887  ...         0.642750  -1.296535
27      1.272034      0.223284  ...        -0.139382  -1.296535
28      0.332773      1.390444  ...         0.841838  -1.296535
29      0.976918     -0.985727  ...         0.150007  -1.296535
..           ...           ...  ...              ...        ...
539    -1.826391      1.429970  ...        -0.688296   0.769931
540    -0.734182     -1.127554  ...         0.247418   0.769931
541     0.097248      1.325344  ...        -0.568132   0.769931
542     0.173865      1.425320  ...        -0.967730   0.769931
543    -0.260295      2.039125  ...        -0.686163   0.769931
544    -0.073010      0.327910  ...        -0.041260   0.769931
545    -0.143951      0.916140  ...        -0.277321   0.769931
546    -1.080374     -0.683475  ...        -0.143648   0.769931
547    -1.097400     -0.629999  ...        -0.539691   0.769931
548    -1.261132      0.011707  ...        -0.814148   0.769931
549    -0.938492      1.143992  ...        -1.026746   0.769931
550    -0.927141      0.509261  ...        -1.567838   0.769931
551    -0.850525      0.732463  ...        -0.049792   0.769931
552    -0.385151      2.357653  ...        -0.967019   0.769931
553    -1.360450      0.616212  ...        -0.281587   0.769931
554    -0.353937      2.239077  ...        -1.075807   0.769931
555    -1.088887      1.934499  ...        -0.430903   0.769931
556    -1.125777      0.069832  ...         0.280125   0.769931
557    -1.334911      1.997275  ...        -1.075807   0.769931
558     0.131300      0.788264  ...        -0.826946   0.769931
559    -0.742695      1.078892  ...        -0.266656   0.769931
560    -0.021933      1.827549  ...         0.208311   0.769931
561    -0.830662      2.343703  ...        -1.555040   0.769931
562     0.310072      2.634331  ...         0.600088  -1.296535
563     1.927530      1.348594  ...         0.962713  -1.296535
564     2.109139      0.720838  ...         1.040926  -1.296535
565     1.703356      2.083301  ...         0.102368  -1.296535
566     0.701667      2.043775  ...        -0.839745  -1.296535
567     1.836725      2.334403  ...         1.524426  -1.296535
568    -1.806811      1.220718  ...        -3.109349   0.769931

[569 rows x 6 columns]

In [0]:
dataframe.mean()

mean_radius       -3.136331e-15
mean_texture      -6.558316e-15
mean_perimeter    -7.012551e-16
mean_area         -8.339355e-16
mean_smoothness    6.120470e-15
diagnosis          1.050127e-15
dtype: float64

In [0]:
x = data1.iloc[:, : -1]
y = data1.iloc[:, -1]

In [0]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test =train_test_split(x, y, test_size = 0.3)

In [0]:
x_test.shape

(171, 5)

In [0]:
x_train.shape

(398, 5)