In [0]:
import numpy as np
import pandas as pd
from numpy import linalg as LA

In [0]:
df = pd.read_csv("iris data without class label.csv", header = None)

In [0]:
df.head()

     0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [0]:
# covariance matrix
df3 = df.cov()
df3.shape
df3

          0         1         2         3
0  0.685694 -0.039268  1.273682  0.516904
1 -0.039268  0.188004 -0.321713 -0.117981
2  1.273682 -0.321713  3.113179  1.296387
3  0.516904 -0.117981  1.296387  0.582414

In [0]:
# correlation matrix
df.corr()

          0         1         2         3
0  1.000000 -0.109369  0.871754  0.817954
1 -0.109369  1.000000 -0.420516 -0.356544
2  0.871754 -0.420516  1.000000  0.962757
3  0.817954 -0.356544  0.962757  1.000000

In [0]:
# standardization
df2 = (df - df.mean())/df.std()
# df2

In [0]:
df2

            0         1         2         3
0   -0.897674  1.028611 -1.336794 -1.308593
1   -1.139200 -0.124540 -1.336794 -1.308593
2   -1.380727  0.336720 -1.393470 -1.308593
3   -1.501490  0.106090 -1.280118 -1.308593
4   -1.018437  1.259242 -1.336794 -1.308593
5   -0.535384  1.951133 -1.166767 -1.046525
6   -1.501490  0.797981 -1.336794 -1.177559
7   -1.018437  0.797981 -1.280118 -1.308593
8   -1.743017 -0.355171 -1.336794 -1.308593
9   -1.139200  0.106090 -1.280118 -1.439627
10  -0.535384  1.489872 -1.280118 -1.308593
11  -1.259964  0.797981 -1.223442 -1.308593
12  -1.259964 -0.124540 -1.336794 -1.439627
13  -1.863780 -0.124540 -1.506822 -1.439627
14  -0.052331  2.181763 -1.450146 -1.308593
15  -0.173094  3.104284 -1.280118 -1.046525
16  -0.535384  1.951133 -1.393470 -1.046525
17  -0.897674  1.028611 -1.336794 -1.177559
18  -0.173094  1.720502 -1.166767 -1.177559
19  -0.897674  1.720502 -1.280118 -1.177559
20  -0.535384  0.797981 -1.166767 -1.308593
21  -0.897674  1.489872 -1.280118 -1.046525
22  -1.501490  1.259242 -1.563497 -1.308593
23  -0.897674  0.567351 -1.166767 -0.915491
24  -1.259964  0.797981 -1.053415 -1.308593
25  -1.018437 -0.124540 -1.223442 -1.308593
26  -1.018437  0.797981 -1.223442 -1.046525
27  -0.776911  1.028611 -1.280118 -1.308593
28  -0.776911  0.797981 -1.336794 -1.308593
29  -1.380727  0.336720 -1.223442 -1.308593
..        ...       ...       ...       ...
120  1.276066  0.336720  1.100267  1.443121
121 -0.293857 -0.585801  0.646860  1.050019
122  2.242172 -0.585801  1.667025  1.050019
123  0.551486 -0.816431  0.646860  0.787951
124  1.034539  0.567351  1.100267  1.181053
125  1.638355  0.336720  1.270294  0.787951
126  0.430722 -0.585801  0.590184  0.787951
127  0.309959 -0.124540  0.646860  0.787951
128  0.672249 -0.585801  1.043591  1.181053
129  1.638355 -0.124540  1.156943  0.525883
130  1.879882 -0.585801  1.326970  0.918985
131  2.483699  1.720502  1.496998  1.050019
132  0.672249 -0.585801  1.043591  1.312087
133  0.551486 -0.585801  0.760212  0.394849
134  0.309959 -1.047062  1.043591  0.263815
135  2.242172 -0.124540  1.326970  1.443121
136  0.551486  0.797981  1.043591  1.574155
137  0.672249  0.106090  0.986915  0.787951
138  0.189196 -0.124540  0.590184  0.787951
139  1.276066  0.106090  0.930239  1.181053
140  1.034539  0.106090  1.043591  1.574155
141  1.276066  0.106090  0.760212  1.443121
142 -0.052331 -0.816431  0.760212  0.918985
143  1.155302  0.336720  1.213619  1.443121
144  1.034539  0.567351  1.100267  1.705189
145  1.034539 -0.124540  0.816888  1.443121
146  0.551486 -1.277692  0.703536  0.918985
147  0.793012 -0.124540  0.816888  1.050019
148  0.430722  0.797981  0.930239  1.443121
149  0.068433 -0.124540  0.760212  0.787951

[150 rows x 4 columns]

In [0]:
# covariance matrix
df4 = df2.cov()

In [0]:
# eigenvector
w, v = LA.eig(df4)
print(w) # eigenvalue
v = v.T
print(v) # eigenvector

[2.91081808 0.92122093 0.14735328 0.02060771]
[[ 0.52237162 -0.26335492  0.58125401  0.56561105]
 [-0.37231836 -0.92555649 -0.02109478 -0.06541577]
 [-0.72101681  0.24203288  0.14089226  0.6338014 ]
 [ 0.26199559 -0.12413481 -0.80115427  0.52354627]]

In [0]:
df = np.hstack((v[0].reshape(4, 1), v[1].reshape(4, 1)))

In [0]:
df.shape

(4, 2)

In [0]:
res = df2.dot(df)

In [0]:
res

            0         1
0   -0.230885 -0.876737
1    0.072288  0.254177
2   -0.184750 -0.122856
3   -0.243694  0.149844
4   -0.379836 -1.058395
5   -0.439039 -1.817373
6   -0.426103 -0.520524
7   -0.248964 -0.617755
8   -0.157261  0.626656
9   -0.088774  0.070699
10  -0.254235 -1.385353
11  -0.415995 -0.540430
12  -0.025126  0.302247
13  -0.217949  0.420112
14  -0.136913 -2.194104
15  -0.597400 -3.007526
16  -0.275582 -1.872243
17  -0.196554 -0.893003
18  -0.198251 -1.683057
19  -0.495022 -1.519670
20  -0.078360 -0.717534
21  -0.374824 -1.322474
22  -0.468712 -0.986050
23  -0.078751 -0.457460
24  -0.538588 -0.499278
25   0.053643  0.249808
26  -0.221168 -0.636569
27  -0.208666 -0.894823
28  -0.081934 -0.695079
29  -0.307343 -0.081704
..        ...       ...
120  0.125994 -0.560553
121 -0.126695  0.645798
122  0.462499  0.224836
123  0.332096  0.669166
124 -0.154701 -0.677875
125  0.020999 -0.533482
126  0.224009  0.473791
127 -0.051675  0.092389
128  0.126252  0.471125
129  0.205803 -0.101462
130  0.484104  0.254208
131 -0.147421 -2.014538
132  0.160583  0.454860
133  0.061508  0.531937
134 -0.131574  1.107320
135  0.638939 -0.333189
136 -0.349047 -0.826637
137 -0.193478 -0.134179
138 -0.073894  0.110475
139  0.265794 -0.355712
140  0.160890 -0.313467
141  0.457047 -0.429396
142 -0.030719  0.839353
143 -0.018818 -0.501314
144 -0.017380 -0.742939
145  0.375884 -0.138610
146  0.497297  1.093540
147  0.146726 -0.026205
148 -0.364733 -0.806002
149 -0.259570  0.183431

[150 rows x 2 columns]

In [0]:
from sklearn.decomposition import PCA as sklearnPCA
sklearn_pca = sklearnPCA(n_components=2)
Y_sklearn = sklearn_pca.fit_transform(df2)

In [0]:
new = pd.DataFrame(Y_sklearn)
new

            0         1
0   -2.256981  0.504015
1   -2.079459 -0.653216
2   -2.360044 -0.317414
3   -2.296504 -0.573447
4   -2.380802  0.672514
5   -2.063623  1.513478
6   -2.437545  0.074314
7   -2.226383  0.246787
8   -2.334138 -1.091490
9   -2.181368 -0.447131
10  -2.156263  1.067021
11  -2.319607  0.158058
12  -2.216657 -0.706750
13  -2.630902 -0.935149
14  -2.184972  1.883668
15  -2.243948  2.713281
16  -2.195396  1.508696
17  -2.182866  0.512587
18  -1.887750  1.426332
19  -2.332136  1.154167
20  -1.908164  0.429028
21  -2.197284  0.949277
22  -2.764907  0.487883
23  -1.814333  0.106394
24  -2.220778  0.161645
25  -1.950490 -0.605863
26  -2.045212  0.265126
27  -2.160954  0.550173
28  -2.133160  0.335516
29  -2.261215 -0.313827
..        ...       ...
120  2.033683  0.904369
121  0.970663 -0.569267
122  2.888388  0.396463
123  1.324756 -0.485135
124  1.698550  1.010762
125  1.951191  0.999984
126  1.167992 -0.317832
127  1.016376  0.065324
128  1.780046 -0.192627
129  1.858552  0.553527
130  2.427365  0.245831
131  2.308349  2.617415
132  1.854160 -0.184056
133  1.107561 -0.294998
134  1.193471 -0.814439
135  2.791597  0.841928
136  1.574879  1.068894
137  1.342547  0.420846
138  0.920350  0.019166
139  1.847363  0.670178
140  2.009425  0.608359
141  1.896763  0.683734
142  1.149339 -0.698984
143  2.036486  0.861798
144  1.995008  1.045049
145  1.864277  0.381544
146  1.553288 -0.902291
147  1.515767  0.265904
148  1.371796  1.012968
149  0.956096 -0.022210

[150 rows x 2 columns]

In [0]:
Da